#!/usr/bin/env python3
"""Run every Tier-1/Tier-2 case and regenerate the suite headline artifacts."""
from __future__ import annotations
import argparse,csv,json,subprocess
from pathlib import Path

ROOT=Path(__file__).parent
CASES=sorted((ROOT/'cases').iterdir(), key=lambda p:(int(p.name.split('-')[0][1:]), int(p.name.split('-')[1].split('_')[0])))

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--skip-run',action='store_true',help='collect existing result.json files without rerunning solvers'); args=ap.parse_args()
    rows=[]
    for case in CASES:
        if not case.is_dir(): continue
        if not args.skip_run:
            # Case scripts write their evidence into ``out/`` and ``result.json``;
            # keep the suite driver quiet so a long transient does not drown out
            # the case-level verdicts.
            subprocess.run(['./run.sh'],cwd=case,check=True,stdout=subprocess.DEVNULL)
        result=json.loads((case/'result.json').read_text()); ref=json.loads((case/'reference.json').read_text())
        conv=result.get('convergence') or {}; err=result.get('error') or {}
        tol=result.get('tolerance') or {}
        rows.append({'case_id':result.get('case_id',case.name),'capability':result.get('capability',''),'checklist_item':ref.get('checklist_item',''),'validation_class':result.get('validation_class',''),'reference_value':result.get('reference_value'),'moose_value':result.get('moose_value'),'units':result.get('units',''),'scored_metric':tol.get('metric',''),'scored_error':err.get('relative') if err.get('relative') is not None else err.get('absolute'),'tolerance':tol.get('value'),'observed_order':conv.get('observed_order'),'verdict':result.get('verdict',''),'runtime_s':result.get('runtime_s',0)})
    (ROOT/'data').mkdir(exist_ok=True)
    fields=list(rows[0]) if rows else []
    with (ROOT/'data/summary.csv').open('w',newline='') as f:
        w=csv.DictWriter(f,fieldnames=fields); w.writeheader(); w.writerows(rows)
    lines=['# RESULTS','', 'Generated by `python run_all.py --skip-run` from the case `result.json` artifacts.','',
           '**Reading the table.** *Scored error* is the quantity named in *Scored metric*, compared against',
           '*Tolerance*. It is the number the verdict is based on, and for several cases it is deliberately',
           'NOT `|MOOSE - Reference|`: where the scored metric is a profile norm (T1-07, T2-13, T2-16, T2-20)',
           'the Reference and MOOSE columns carry a single representative physical value while the verdict',
           'rests on the whole profile. Reading the first three columns as a subtraction will mislead.','',
           '| Case | Capability | Class | Reference | MOOSE | Scored metric | Scored error | Tolerance | Verdict |',
           '|---|---|:---:|---:|---:|---|---:|---:|:---:|']
    for r in rows:
        def fmt(v): return '—' if v is None else (f'{v:.4g}' if isinstance(v,(float,int)) else str(v))
        lines.append(f"| `{r['case_id']}` | {r['capability']} | [{r['validation_class']}] | {fmt(r['reference_value'])} {r['units']} | {fmt(r['moose_value'])} | {r['scored_metric']} | {fmt(r['scored_error'])} | {fmt(r['tolerance'])} | **{r['verdict']}** |")
    lines += ['', 'Validation classes: [A] verification against a closed form or invariant; [B] benchmark/code comparison; [E] experiment. PASS/FAIL/PARTIAL/BLOCKED are reported without post hoc tolerance changes.']
    (ROOT/'RESULTS.md').write_text('\n'.join(lines)+'\n')
    print(f'Collected {len(rows)} cases; wrote data/summary.csv and RESULTS.md')

if __name__=='__main__': main()
